### PR TITLE
Some UI enhancements

### PR DESCRIPTION
**Pull request by patricks**
- Removed the extra navigation controller so this behaves more like a master - detail scene.
- Removed the background color of the activity icons, looks better if you select a workout.
- Updated cell style of the main view controller a little bit.
- Added sketch file with the new artwork.

### CODE REVIEW

**Comment by mgmart** [comment]
Sounds great. 
I was on vacation. I suppose I need some more days before being able to test and merge.

**Comment by patricks** [comment]
😊. I have a few more ideas. Maybe I should create issues for every feature/enhancement. So we can discuss before every implementation?

**Comment by mgmart** [comment]
Maybe we can arrange a call and discuss it more directly. I suppose we're both German speaking.

**Comment by patricks** [comment]
Send you a DM in Twitter 😉

**Pull request merged**
