### PR TITLE
Updated WorkoutsTableViewController

### PR DESCRIPTION
**Pull request by patricks**
Updated the WorkoutsTableViewController Design

img_2920

### CODE REVIEW

**Comment by mgmart** [comment]
The cycling icon seems a bit misplaced because it's smaller in height than the others. Could that be solved by making the icons a bit bigger?

BTW: The outer ring of the wheels were a bit damaged by adding the transparent background.

screen_shot_2019-01-26_at_05_11_11

**Comment by patricks** [comment]
I’ll check this icon, maybe I can simplify it a bit. Do you like the new TablieView style in general?

**Comment by mgmart** [comment]
> I’ll check this icon, maybe I can simplify it a bit. Do you like the new TablieView style in general?

Year, please go on. I”m just trying to do some QA :)

**Comment by patricks** [comment]
I have updated the icons a little bit.

img_2922

**Comment by mgmart** [comment]
It looks definitely nicer than my attempt.

Thank you.

**Pull request merged**
